### PR TITLE
Fixed handling of UTF-8 paths for world files opened from Windows GUI

### LINKED ISSUE #2744: Incorrect handling of greek characters in file path cause Webots crash when starting the program from a wbt file
**Describe the Bug**
If you try to start Webots from a wbt file (double-click) that is located inside a folder with a greek name, Webots will start, show a "Couldn't open file" error and instantly terminate. The file path shown has gibberish letters in the greek folder part of it
greek-chars

Opening the file from the open world menu works fine, but this issue may happen with other characters as well

**Steps to Reproduce**
1. Create a folder with greek characters
2. Place the 'worlds' folder with a wbt file inside
3. Double click on the wbt file

**Expected behavior**
Webots should normally load the world

**Screenshots**
https://user-images.githubusercontent.com/12613442/107705062-deaaec00-6cc6-11eb-9841-ad28f7e232ad.png

**System**
 - Operating System: Windows 10 Pro
 - Graphics Card: NVIDIA GeForce GTX 1050 6GB

### PR DESCRIPTION
**Pull request by omichel**
Fixes  #2744.

### CODE REVIEW

File: src/webots/launcher/launcher.c [hunk 1]
```diff
@@ -51,46 +51,42 @@ static int fail(const char *function, const char *info) {
...
+  const wchar_t *find = wcsstr(original_command_line, L"\\msys64\\mingw64\\bin\\webots");
+  int index = find - original_command_line;
+  index += 26;
+  wcsncpy(command_line, original_command_line, index);
+  command_line[index++] = '-';
+  command_line[index++] = 'b';
+  command_line[index++] = 'i';
+  command_line[index++] = 'n';
+  for (; original_command_line[index - 4]; index++)
+    command_line[index] = original_command_line[index - 3];
```
Comment (stefaniapedrazzi) [inline src/webots/launcher/launcher.c:65]: I don't get exactly why here is `index - 3` instead of `index - 4`.
But in general it would be good to add some comments explaining what this piece of code is doing.

**Review by stefaniapedrazzi — COMMENTED** [review]
The code seems fine. Just have a minor comment.

**Review by stefaniapedrazzi — CHANGES_REQUESTED** [review]
Thank you!

Everything looks fine for me now.
There is just one last typo to fix.

**Review by stefaniapedrazzi — APPROVED** [review]
