### PR TITLE
Fixed controller args with double quotes

### LINKED ISSUE #1712: Broken Controller Arguments
**Describe the Bug**
The controller arguments are broken (at least in python).

**Steps to Reproduce**
1. Open and run the pedestrian world.

**Screenshots**
The starting command line looks wrong:
```
INFO: pedestrian: Starting controller: python!-u+pedestrian.py+--trajectory="0+3,+0+-3"+--speed=2.5
```

The controllers fails:
```
[pedestrian] Usage: pedestrian.py [options]
[pedestrian] 
[pedestrian] pedestrian.py: error: no such option: -3
WARNING: 'pedestrian' controller exited with status: 2.
[pedestrian] Usage: pedestrian.py [options]
```

This has probably been introduced in #1709.

### PR DESCRIPTION
**Pull request by omichel**
Fixes #1712.

Note: This is a quick & dirty fix until we introduce `Robot.controllerArgs` as a `MFString` instead of a `SFString` that will provide a much better interface.

### CODE REVIEW

**Comment by DavidMansolino** [comment]
:eyes:

File: src/webots/control/WbController.cpp [hunk 1]
```diff
@@ -887,6 +883,25 @@ const QString &WbController::args() const {
   return mRobot->controllerArgs();
 }
 
+QStringList WbController::argsList() const {
```
Comment (DavidMansolino) [inline src/webots/control/WbController.cpp:886]: This function would deserve a few comments in the code.

**Comment by omichel** [comment]
I believe it is correct to remove the quotes. This is actually done by the system before passing the arguments to the program.

File: src/webots/control/WbController.cpp [hunk 2]
```diff
@@ -887,6 +883,25 @@ const QString &WbController::args() const {
...
+  const QString args = mRobot->controllerArgs().trimmed();
+  if (args.length() == 0)
+    return list;
+  bool quote = false;
+  int previous = 0;
+  for (int i = 0; i < args.length(); i++) {
+    if (args[i] == '"')
+      quote = !quote;
+    if (args[i] == ' ' && !quote) {
+      list << args.mid(previous, i - previous - 1).replace("\"", "");
```
Comment (DavidMansolino) [inline src/webots/control/WbController.cpp:897]:
```suggestion
      const QString argument = args.mid(previous, i - previous).replace("\"", "").trimmed();
      if (!argument.isEmpty())
        list << args.mid(previous, i - previous).replace("\"", "");
```

The problem was indeed not the removed quotes, but there were actually to issues on this line:
  1. if more than one space was used between arguments, then some empty arguments were pushed in the list.
  2. the cutting of the arguments was wrong. This was actually visible in the starting sequence I send before (but I just saw it know): `... --initial-linear-velocity= --initial-angular-velocity=0. --are...` (last character of each argument is missing).
