### PR TITLE
Fixed hang after copy/paste of robots on Linux

### LINKED ISSUE #4716: Copying a robot blocks the simulation
Steps to reproduce:
1) open `accelerometer.wbt`
2) run simulation
3) copy `MyBot` robot
-> simulation blocks for long time (many minutes)

After some time the following errors are printed in the console:
```
Cannot connect to Webots instance on socket "/tmp/webots-1234/ipc/MyBot%281%29/intern", retrying in 0 second...
Cannot connect to Webots instance on socket "/tmp/webots-1234/ipc/MyBot%281%29/intern", retrying in 1 second...
Cannot connect to Webots instance on socket "/tmp/webots-1234/ipc/MyBot%281%29/intern", retrying in 2 seconds...
Cannot connect to Webots instance on socket "/tmp/webots-1234/ipc/MyBot%281%29/intern", retrying in 3 seconds...
Cannot connect to Webots instance on socket "/tmp/webots-1234/ipc/MyBot%281%29/intern", retrying in 4 seconds...
Cannot connect to Webots instance on socket "/tmp/webots-1234/ipc/MyBot%281%29/intern", retrying in 5 seconds...
Cannot connect to Webots instance on socket "/tmp/webots-1234/ipc/MyBot%281%29/intern", retrying in 6 seconds...
Cannot connect to Webots instance on socket "/tmp/webots-1234/ipc/MyBot%281%29/intern", retrying in 7 seconds...
Cannot connect to Webots instance on socket "/tmp/webots-1234/ipc/MyBot%281%29/intern", retrying in 8 seconds...
Cannot connect to Webots instance on socket "/tmp/webots-1234/ipc/MyBot%281%29/intern", retrying in 9 seconds...
Cannot connect to Webots instance on socket "/tmp/webots-1234/ipc/MyBot%281%29/intern", retrying in 10 seconds...
Cannot connect to Webots instance on socket "/tmp/webots-1234/ipc/MyBot%281%29/intern", retrying in 11 seconds...
Giving up...
WARNING: 'accelerometer' controller exited with status: 1.
```

**Expected behavior**
Webots should not block and the old and new robots should move immediately.

### PR DESCRIPTION
**Pull request by omichel**
Fixes #4716.

### CODE REVIEW

File: src/webots/control/WbController.cpp [hunk 1]
```diff
@@ -304,8 +304,12 @@ void WbController::start() {
         mType = WbFileUtil::EXECUTABLE;
     }
   }
-  // recover from a crash, when the previous server instance has not been cleaned up
-
+  // check if robot was renamed before it started (this happens in case of copy/paste of the robot)
```
Comment (ad-daniel) [inline src/webots/control/WbController.cpp:307]:
```suggestion
  // check if the robot was renamed before it started (this happens in case of copy/paste of the robot)
```

**Review by ad-daniel — CHANGES_REQUESTED** [review]
I'm not sure if it's related to the same original issue but if I:

- run the simulation a few seconds and pause it
- copy and paste the robot minimum 2 times (doesn't trigger for just 1 paste)
- I get:

```
ERROR: Cannot listen to the local server (server name = '/tmp/webots-1234/ipc/MyBot%282%29/intern'): QLocalServer::listen: Name error`
```

**Comment by ad-daniel** [comment]
Not sure if something is wrong on my end, but it seems I can't run the simulation anymore (the unmodified world)

**Comment by omichel** [comment]
I can indeed reproduce the problem, will investigate...

**Comment by omichel** [comment]
> Not sure if something is wrong on my end, but it seems I can't run the simulation anymore (the unmodified world)

I believe I fixed the problem. Sorry for the trouble...
