### PR TITLE
Fixed random triangle mesh collision detection bug

### LINKED ISSUE #1975: Sojourner move through rocks
**Describe the Bug**
The Sojourner moves through the rock as if it was not there:
sojourner

### PR DESCRIPTION
**Pull request by omichel**
Fixes #1975.

The triangle mesh passed to ODE trimesh constructor was wrong. The number of vertices was three times too much causing ODE to read uninitialized garbage data beyond the actual vertices data, sometimes including nan values and other oddities. This was causing the AABB of the resulting mesh to be wrong, and the ODE "near" callback was never called, thus missing the collision detection.

### CODE REVIEW

**Comment by omichel** [comment]
This bug was likely caused by the poor naming of a member field: `mVertices` was an array of double values representing the coordinates of the vertices of the mesh and the method `numberOfVertices()` was returning `mVertices.size()` which was wrong.
I basically renamed `mVertices` to `mCoordinates` and changed the `numberOfVertices()` method to return `mCoordinates.size() / 3`. Hopefully, this will help to prevent future similar bugs...

**Comment by omichel** [comment]
This PR seems to fix #1971 as well (tested under Windows).

**Comment by DavidMansolino** [comment]
:eyes:

File: src/webots/nodes/WbTriangleMeshGeometry.cpp [hunk 1]
```diff
@@ -299,10 +299,9 @@ void WbTriangleMeshGeometry::setOdeTrimeshData() {
   const int n = mTriangleMesh->numberOfVertices();
   const int nt = mTriangleMesh->numberOfTriangles();
   mTrimeshData = dGeomTriMeshDataCreate();
-  mScaledVerticesNeedUpdate = true;
-  updateScaledVertices();
-
-  dGeomTriMeshDataBuildDouble(mTrimeshData, mTriangleMesh->scaledVerticesData(), 3 * sizeof(double), n,
+  mScaledCoordinatesNeedUpdate = true;
+  updateScaledCoordinates();
+  dGeomTriMeshDataBuildDouble(mTrimeshData, mTriangleMesh->scaledCoordinatesData(), 3 * sizeof(double), n,
```
Comment (DavidMansolino) [inline src/webots/nodes/WbTriangleMeshGeometry.cpp:304]:
```suggestion
  dGeomTriMeshDataBuildDouble(mTrimeshData, mTriangleMesh->scaledVerticesData(), 3 * sizeof(double), n,
```

File: src/webots/nodes/WbTriangleMeshGeometry.cpp [hunk 2]
```diff
@@ -491,17 +490,17 @@ void WbTriangleMeshGeometry::recomputeBoundingSphere() const {
...
 }
 
-void WbTriangleMeshGeometry::updateScaledVertices() const {
-  if (mScaledVerticesNeedUpdate) {
+void WbTriangleMeshGeometry::updateScaledCoordinates() const {
+  if (mScaledCoordinatesNeedUpdate) {
     const WbVector3 &s = absoluteScale();
-    mTriangleMesh->updateScaledVertices(s.x(), s.y(), s.z());
-    mScaledVerticesNeedUpdate = false;
+    mTriangleMesh->updateScaledCoordinates(s.x(), s.y(), s.z());
```
Comment (DavidMansolino) [inline src/webots/nodes/WbTriangleMeshGeometry.cpp:496]:
```suggestion
    mTriangleMesh->updateScaledVertices(s.x(), s.y(), s.z());
```
