### PR TITLE
Change Python installation detection for macOS

### LINKED ISSUE #3925: Incorrect Python version used when importing controller?
**Describe the Bug**
When starting a world with Python controller used, it failed with the following error

```
INFO: referee: Starting controller: /usr/local/Cellar/python@3.9/3.9.8/bin/python3.9 -u referee.py
Traceback (most recent call last):
  File ".../controllers/referee/referee.py", line 14, in <module>
    from controller import Supervisor, AnsiCodes, Node
  File "/Applications/Webots.app/lib/controller/python39/controller.py", line 31, in <module>
    import _controller
ImportError: dlopen(/Applications/Webots.app/lib/controller/python39/_controller.so, 2): Library not loaded: /Library/Frameworks/Python.framework/Versions/3.9/Python
  Referenced from: /Applications/Webots.app/lib/controller/python39/_controller.so
  Reason: image not found
WARNING: 'referee' controller exited with status: 1.
```

I've found in `/Applications/Webots.app/lib/controller` there are folders `python39` and `python39_brew`. So, I guess they are for system's bundled Python and one installed with Homebrew.

If I remove the `python39` folder contents and instead of it put the one from `python39_brew` folder, my world starts successfully without any errors.

In the webots settings python is set to exact location on Homebrew Python 3.9 - /usr/local/Cellar/python@3.9/3.9.8/bin/python3.9

So, webots somehow uses incorrect include paths or something?

**System**
 - macOS BigSur
 - Python 3.9 from Homebrew
 - Webots 2021b

### PR DESCRIPTION
**Pull request by Olegas**
**Description**
On some systems detecting a Python installation path gives incorrect result. In example:
```
/usr/local/Cellar/python@3.9/3.9.8/bin/python3.9 -c 'import sys; print(sys.exec_prefix)'
/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9
```

The solution is to not execute Python at all and just compare `mPythonCommand` against `/usr/local/Cellar`. In this case a user can explicitly declare the version they uses by setting it in Webots settings.

**Related Issues**
This fixes #3925

### CODE REVIEW

File: src/webots/control/WbController.cpp [hunk 1]
```diff
@@ -514,13 +514,7 @@ void WbController::setProcessEnvironment() {
...
     }
 #ifdef __APPLE__
-    QProcess process;
-    process.setProcessEnvironment(env);
-    process.start(mPythonCommand, QStringList() << "-c"
-                                                << "import sys; print(sys.exec_prefix);");
-    process.waitForFinished();
-    const QString output = process.readAll();
-    if (output.startsWith("/usr/local/Cellar"))
+    if (mPythonCommand.startsWith("/usr/local/Cellar"))
```
Comment (omichel) [inline src/webots/control/WbController.cpp:517]: I fear that this might be a problem if users simply set `"python"` in `mPythonCommand` and modify their PATH environment variable prepending `/usr/local/Cellar/python@3.9/3.9.8/bin/` to find it there. Therefore, a better fix could be (not tested):
```suggestion
    QProcess process;
    process.setProcessEnvironment(env);
    process.start("which", QStringList() << mPythonCommand);
    process.waitForFinished();
    const QString output = process.readAll();
    if (output.startsWith("/usr/local/Cellar/python@"))
```
May I kindly ask you to test it?

Comment (Olegas) [reply src/webots/control/WbController.cpp:517]: Sure!

Comment (Olegas) [reply src/webots/control/WbController.cpp]: This work fine. I've updated my branch (squash + rebase onto master)

**Review by omichel — APPROVED** [review]
Thank you!

**Comment by Olegas** [comment]
@omichel can I merge?

**Comment by omichel** [comment]
> @omichel can I merge?

Sure.
