### PR TITLE
Fix GPU tests

### LINKED ISSUE #2588: incorrect detection of GPU memory on iMac 2020
**Describe the Bug**
On starting WeBots 2021a for the first time, it generates a warning that my system is below minimum requirements having less than 2Gb of memory. However, "About this Mac" reports an AMD Radeon Pro 5500 XT 8 GB card. (iMac 20,1)

**Steps to Reproduce**
See above

**Expected behavior**
No error and a dawning realization that this is a sufficient graphics card to run Webots uninhibited.

**Screenshots**

**System**
 - Operating System: MacOS Catalina
 - Graphics Card: AMD Radeon Pro 5500 XT 8 GB

**Additional context**

### PR DESCRIPTION
**Pull request by omichel**
Fixes #2588.

In addition to fixing #2588, this PR also removes some annoying warnings with recent Intel or AMD graphics cards which support OpenGL very well and should not cause such warnings.

Our [telemetry](https://cyberbotics.com/telemetry) reports the following GPU usage: [gpu.txt](https://github.com/cyberbotics/webots/files/5769060/gpu.txt)

### CODE REVIEW

File: src/webots/core/WbSysInfo.cpp [hunk 1]
```diff
@@ -498,4 +498,35 @@ bool WbSysInfo::isAmdLowEndGpu(QOpenGLFunctions *gl) {
...
+  if (lowEndGpu == -1) {       // based on the telemetry data from https://cyberbotics.com/telemetry
+    lowEndGpu = 0;
+    const QString &renderer = openGLRenderer();
+    if (renderer.contains("Intel") && renderer.contains(" HD Graphics ")) {
+      // we support only recent Intel GPUs from about 2015
+      if (renderer.contains("Ivybridge") || renderer.contains("Sandybridge") || renderer.contains("Haswell") ||
+          renderer.contains("Ironlake"))
+        lowEndGpu = 1;
+      else {
+        const int modelIndex = renderer.indexOf(" HD Graphics ") + 13;
```
Comment (lukicdarkoo) [inline src/webots/core/WbSysInfo.cpp:514]: Can we use regex here? It would be more readable

Comment (omichel) [reply src/webots/core/WbSysInfo.cpp]: You are right, this is much more readable with regex.

**Review by lukicdarkoo — APPROVED** [review]
Thank you
