### PR TITLE
Fix Camera Reset

### LINKED ISSUE #1778: does not work robotis-op2 camera after simulation reset
**Describe the Bug**

**Steps to Reproduce**
1. ' generate a controller and a supervisor for op2. '
2. 'use your new simulation reset command in supervisor'
3. run for your controller for one step then see reset and the first position of robot.
4. Check the camera image. It is one before reset. Please see it. 
5. I can see new images in screen. However I cant receive no more change in the camera array. 
by using camera.getImageArray()).

**Expected behavior**
After reset, it is expected to change the images taken by using camera.getImageArray())

**Screenshots**

**System**
 - Operating System: [e.g., Windows 10, Linux Ubuntu 18.04, macOS Mojave]
 - Graphics Card: [e.g., NVIDIA GeForce RTX 2080 11 GB, AMD Radeon RX 580 8GB, etc.]

**Additional context**

### PR DESCRIPTION
**Pull request by DavidMansolino**
**Description**
Fix #1778.

### CODE REVIEW

**Comment by DavidMansolino** [comment]
:heavy_check_mark:: travis_unit

**Comment by omichel** [comment]
:eyes:

File: src/webots/nodes/WbRobot.cpp [hunk 1]
```diff
@@ -981,6 +983,8 @@ void WbRobot::dispatchAnswer(QDataStream &stream, bool includeDevices) {
       }
     }
   } else {
+    if (mNeedToForceTime)
+      writeAnswer(stream);
```
Comment (omichel) [inline src/webots/nodes/WbRobot.cpp:987]: Are you sure this is needed as `writeAnswer()` is called anyhow on line 993?

Comment (DavidMansolino) [reply src/webots/nodes/WbRobot.cpp:987]: Yes, this is actually the main point of the fix, in the specific reset case we need to make sure that the robot messages are sent before the device ones to update the time.
If we want to avoid calling it a second time, we could add a kind of `if (!mNeedToForceTime)` for the second call but IMO this complexifies the code uselessly (as the second call to writeAnswer will strictly do nothing as all the messages are already sent).

Comment (omichel) [reply src/webots/nodes/WbRobot.cpp:987]: OK, and why do we need to send the Robot answer after the device answers in the normal case? I am afraid the reset case will change this and it may have some side effect. If there is no reason for sending the robot answer after, we should send it before in all cases.

Comment (DavidMansolino) [reply src/webots/nodes/WbRobot.cpp:987]: I did not put it by default to the beginning for this purpose. When doing the reset, since the time is reset to 0 it does not cause any problem. But for the other steps, I am afraid of non-evident side effects of increasing the time before sending the device messages.

Comment (omichel) [reply src/webots/nodes/WbRobot.cpp:987]: I see. Thank you for the explanation. I will try to investigate the possible side effects of moving the robot answer before the devices answer, as it seems cleaner (we do that for the configure message).

File: src/lib/Controller/api/abstract_camera.c [hunk 2]
```diff
@@ -138,13 +138,15 @@ void abstract_camera_toggle_remote(WbDevice *d, WbRequest *r) {
...
-  double current_simulation_time = wb_robot_get_time();
+  const double current_simulation_time = wb_robot_get_time();
+  const double previous_image_update_time = ac->image_update_time;  // in case of reset, time can go backward
   if (ac->image_update_time >= current_simulation_time)
     return true;
 
   ac->image_requested = true;
   wb_robot_flush_unlocked();
-  if (ac->image_update_time != current_simulation_time && robot_is_quitting() == 0) {
+  if (ac->image_update_time != current_simulation_time && previous_image_update_time <= ac->image_update_time &&
```
Comment (omichel) [inline src/lib/Controller/api/abstract_camera.c:148]: The new condition seems to be always true, isn't it?

Comment (DavidMansolino) [reply src/lib/Controller/api/abstract_camera.c:148]: No, because the `wb_robot_flush_unlocked` function will increase the `ac->image_update_time` time, therefore `ac->image_update_time == current_simulation_time`, and about `previous_image_update_time <= ac->image_update_time`, this is not true in case of reset, because `ac->image_update_time == 0.0`.

Comment (omichel) [reply src/lib/Controller/api/abstract_camera.c:148]: OK, I see. Thanks for the explanation.

File: src/lib/Controller/api/abstract_camera.c [hunk 3]
```diff
@@ -138,13 +138,15 @@ void abstract_camera_toggle_remote(WbDevice *d, WbRequest *r) {
 }
 
 bool abstract_camera_request_image(AbstractCamera *ac, const char *functionName) {
-  double current_simulation_time = wb_robot_get_time();
+  const double current_simulation_time = wb_robot_get_time();
+  const double previous_image_update_time = ac->image_update_time;  // in case of reset, time can go backward
   if (ac->image_update_time >= current_simulation_time)
```
Comment (omichel) [inline src/lib/Controller/api/abstract_camera.c:143]:
```suggestion
  if (previous_image_update_time >= current_simulation_time)
```
