### PR TITLE
Documentation: fix extracting tabs if version is not specified

### LINKED ISSUE #1296: Broken docs Links with Tab
**Describe the Bug**
When entering a link to the doc with the tab-os or tab-language set, the page is not found and the index is displayed:
https://cyberbotics.com/doc/guide/running-extern-robot-controllers?tab-os=macos&tab-language=python

### PR DESCRIPTION
**Pull request by stefaniapedrazzi**
Fix #1296.

The code to extract queries if the version is not specified has some issues:
* `$version` is not defined 
* regular expression should be adjusted

Moreover the code to parse the query is quite complex.
Using PHP built-in functions to parse the URL and the query string it is possible to simplify it.

URL to check the functionality (after uploading the new version on the server):
https://cyberbotics.com/doc/guide/running-extern-robot-controllers?tab-os=macos&tab-language=python

### CODE REVIEW

File: docs/doc.php [hunk 1]
```diff
@@ -16,60 +16,33 @@ function endsWith($haystack, $needle) {
     exit();
   }
   if ($request_uri == "/doc/blog/index") {
-    header("Location: /doc/blog/Webots-2019-b-release");
+    header("Location: /doc/blog/Webots-2020-a-release");
```
Comment (stefaniapedrazzi) [inline docs/doc.php]: This link should be automatically updated (when updating the release version) or we should document to update it just before the release.

**Comment by stefaniapedrazzi** [comment]
I think it would be good to test this PR directly in production.
I can upload the new version on the website when the reviewer is ready.

File: docs/doc.php (hunk 1 above)
Comment (omichel) [reply docs/doc.php]: Normally, it's done here: https://github.com/cyberbotics/webots/blob/master/src/bin/new_version.sh#L51
Do you think this doesn't work?

**Comment by omichel** [comment]
Can you please upload it on the server so that I can test it now?

**Comment by stefaniapedrazzi** [comment]
I just uploaded it.

File: docs/doc.php (hunk 1 above)
Comment (stefaniapedrazzi) [reply docs/doc.php]: I will check if it works.

Comment (stefaniapedrazzi) [reply docs/doc.php]: I checked and it works fine (also on the develop branch it is correctly set).
So then I don't know why it was wrongly set here.

**Comment by omichel** [comment]
I just noticed that the web page was displaying a warning. I fixed it in 25e4d3f54b228dbdb9d31f2301155c67392f8c29. This was already fixed in the previous `doc.php` online, but apparently this patch was not committed on github.

**Comment by stefaniapedrazzi** [comment]
I also found out that I deleted the instruction setting the repository in case of fork.

**Comment by stefaniapedrazzi** [comment]
If I try to load a documentation with an invalid version I'm still getting an error that quickly disappears, is it this the error that you made silent or was like this even before?

**Comment by omichel** [comment]
No, I silenced another error that was happening on the master branch. We could also silence this one the same way, but it's less important to me.
