### PR TITLE
Fix cppcheck errors

### LINKED ISSUE #1238: New cppcheck errors
**Describe the Bug**
A new version of cppcheck brings many new errors:
```
FAIL: test_projects_with_cppcheck (test_cppcheck.TestCppCheck)
Test projects with Cppcheck.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\webots-r0dha\tests\sources\test_cppcheck.py", line 171, in test_projects_with_cppcheck
    self.run_cppcheck(command)
  File "C:\projects\webots-r0dha\tests\sources\test_cppcheck.py", line 57, in run_cppcheck
    msg='Cppcheck detected some errors:\n\n%s' % reportText
AssertionError: False is not true : Cppcheck detected some errors:
projects\robots\gctronic\e-puck\plugins\robot_windows\botstudio\e-puck\EPuckFacade.cpp:148:27: warning: Either the condition 'groundSensorIndex<NUMBER_OF_GROUND_SENSORS' is redundant or the array 'mGroundSensors[3]' is accessed at index 3, which is out of bounds. [arrayIndexOutOfBoundsCond]
        if (mGroundSensors[groundSensorIndex] == 0)
                          ^
projects\robots\gctronic\e-puck\plugins\robot_windows\botstudio\e-puck\EPuckFacade.cpp:143:31: note: Assuming that condition 'groundSensorIndex<NUMBER_OF_GROUND_SENSORS' is not redundant
        if (groundSensorIndex < NUMBER_OF_GROUND_SENSORS && mGroundSensors[groundSensorIndex] == 0) {
                              ^
projects\robots\gctronic\e-puck\plugins\robot_windows\botstudio\e-puck\EPuckFacade.cpp:148:27: note: Array index out of bounds
        if (mGroundSensors[groundSensorIndex] == 0)
                          ^
projects\robots\kondo\khr-2hv\controllers\khr-2hv_demo\rcb3_simulator.cpp:685:19: style: Obsolete function 'strdup' called. It is recommended to use '_strdup' instead. [strdupCalled]
  motion.m_name = strdup(filename);
                  ^
projects\robots\kondo\khr-2hv\controllers\khr-2hv_demo\rcb3_simulator.cpp:755:25: style: Obsolete function 'strdup' called. It is recommended to use '_strdup' instead. [strdupCalled]
          item.m_name = strdup(buffer + 5);
                        ^
projects\robots\mobsya\thymio\controllers\thymio2_demo\thymio2_demo.c:198:85: style:inconclusive: Boolean expression 'buttons_pressed[0]' is used in bitwise operation. Did you mean '||'? [bitwiseOnBoolean]
    wb_led_set(leds_buttons[LED_BUTTON_BACKWARD], (buttons_pressed[BUTTON_BACKWARD] | buttons_pressed[BUTTON_CENTER]) ? 32 : 0);
                                                                                    ^
projects\robots\mobsya\thymio\controllers\thymio2_demo\thymio2_demo.c:199:83: style:inconclusive: Boolean expression 'buttons_pressed[3]' is used in bitwise operation. Did you mean '||'? [bitwiseOnBoolean]
    wb_led_set(leds_buttons[LED_BUTTON_FORWARD], (buttons_pressed[BUTTON_FORWARD] | buttons_pressed[BUTTON_CENTER]) ? 32 : 0);
                                                                                  ^
projects\robots\mobsya\thymio\controllers\thymio2_demo\thymio2_demo.c:200:79: style:inconclusive: Boolean expression 'buttons_pressed[4]' is used in bitwise operation. Did you mean '||'? [bitwiseOnBoolean]
    wb_led_set(leds_buttons[LED_BUTTON_RIGHT], (buttons_pressed[BUTTON_RIGHT] | buttons_pressed[BUTTON_CENTER]) ? 32 : 0);
                                                                              ^
projects\robots\mobsya\thymio\controllers\thymio2_demo\thymio2_demo.c:201:77: style:inconclusive: Boolean expression 'buttons_pressed[1]' is used in bitwise operation. Did you mean '||'? [bitwiseOnBoolean]
    wb_led_set(leds_buttons[LED_BUTTON_LEFT], (buttons_pressed[BUTTON_LEFT] | buttons_pressed[BUTTON_CENTER]) ? 32 : 0);
                                                                            ^
projects\samples\curriculum\controllers\advanced_slam_2\advanced_slam_2.c:323:11: warning: Either the condition 'robot_x+2>0' is redundant or the array 'om[35][35]' is accessed at index om[-3][*], which is out of bounds. [negativeIndex]
        om[robot_x - 2][robot_y] = (float)1 / (float)19;
          ^
projects\samples\curriculum\controllers\advanced_slam_2\advanced_slam_2.c:322:23: note: Assuming that condition 'robot_x+2>0' is not redundant
      if (robot_x + 2 > 0)
                      ^
projects\samples\curriculum\controllers\advanced_slam_2\advanced_slam_2.c:323:11: note: Negative array index
        om[robot_x - 2][robot_y] = (float)1 / (float)19;
          ^
======================================================================
FAIL: test_sources_with_cppcheck (test_cppcheck.TestCppCheck)
Test Webots with Cppcheck.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\webots-r0dha\tests\sources\test_cppcheck.py", line 136, in test_sources_with_cppcheck
    self.run_cppcheck(command)
  File "C:\projects\webots-r0dha\tests\sources\test_cppcheck.py", line 57, in run_cppcheck
    msg='Cppcheck detected some errors:\n\n%s' % reportText
AssertionError: False is not true : Cppcheck detected some errors:
resources\projects\plugins\robot_windows\generic\generic.c:84:18: style: Obsolete function 'strdup' called. It is recommended to use '_strdup' instead. [strdupCalled]
  char *tokens = strdup(command);
                 ^
resources\projects\plugins\robot_windows\generic\generic.c:135:18: style: Obsolete function 'strdup' called. It is recommended to use '_strdup' instead. [strdupCalled]
  char *tokens = strdup(commands);
                 ^
src\lib\Controller\api\camera.c:482:7: style: Condition 'c' is always true [knownConditionTrueFalse]
  if (c && in_range) {
      ^
src\lib\Controller\api\camera.c:471:7: note: Assuming that condition '!c' is not redundant
  if (!c || !ac) {
      ^
src\lib\Controller\api\camera.c:482:7: note: Condition 'c' is always true
  if (c && in_range) {
      ^
src\lib\Controller\api\robot.c:963:12: style: Obsolete function 'strdup' called. It is recommended to use '_strdup' instead. [strdupCalled]
    pipe = strdup(WEBOTS_SERVER);
           ^
src\lib\Controller\api\robot.c:982:20: style: Obsolete function 'strdup' called. It is recommended to use '_strdup' instead. [strdupCalled]
            pipe = strdup(buffer);
                   ^
src\lib\Controller\api\system.c:80:3: error: Memory leak: w_short_path [memleak]
  return (const char *)buffer;
  ^
src\lib\Controller\api\supervisor.c:1290:9: style: Condition '!filename' is always false [knownConditionTrueFalse]
    if (!filename || !filename[0]) {
        ^
src\lib\Controller\api\supervisor.c:1289:7: note: Assuming that condition 'filename' is not redundant
  if (filename) {
      ^
src\lib\Controller\api\supervisor.c:1290:9: note: Condition '!filename' is always false
    if (!filename || !filename[0]) {
        ^
src\webots\vrml\WbProtoList.hpp:70:3: error: There is an unknown macro here somewhere. Configuration is required. If Q_DISABLE_COPY is a macro then please configure it. [unknownMacro]
  Q_DISABLE_COPY(WbProtoList)
  ^
src\webots\vrml\WbProtoModel.hpp:109:3: error: There is an unknown macro here somewhere. Configuration is required. If Q_DISABLE_COPY is a macro then please configure it. [unknownMacro]
  Q_DISABLE_COPY(WbProtoModel)
  ^
src\webots\nodes\WbBallJoint.cpp:634:25: warning:inconclusive: Possible null pointer dereference: motor2() [nullPointer]
  if (motor2() && motor2()->isPIDPositionControl())
                        ^
src\webots\nodes\WbBallJoint.cpp:642:25: warning:inconclusive: Possible null pointer dereference: motor3() [nullPointer]
  if (motor3() && motor3()->isPIDPositionControl())
                        ^
src\webots\nodes\WbBaseNode.cpp:130:19: warning:inconclusive: Possible null pointer dereference: boundingSphere() [nullPointer]
    boundingSphere()->resetGlobalCoordinatesUpdateTime();
                  ^
src\webots\nodes\utils\WbNodeOperations.cpp:365:15: warning:inconclusive: Either the condition 'sfnode||mfnode' is redundant or there is possible null pointer dereference: mfnode. [nullPointerRedundantCheck]
    success = mfnode->removeNode(node);
              ^
src\webots\nodes\utils\WbNodeOperations.cpp:358:17: note: Assuming that condition 'sfnode||mfnode' is not redundant
  assert(sfnode || mfnode);
                ^
src\webots\nodes\utils\WbNodeOperations.cpp:357:46: note: Assignment 'mfnode=dynamic_cast<WbMFNode*>(parentField->value())', assigned value is 0
  WbMFNode *mfnode = dynamic_cast<WbMFNode *>(parentField->value());
                                             ^
src\webots\nodes\utils\WbNodeOperations.cpp:365:15: note: Null pointer dereference
    success = mfnode->removeNode(node);
              ^
src\wren\StaticMesh.cpp:537:19: style: Variable 'hash' is assigned a value that is never used. [unreadVariable]
    uint64_t hash = cache::sipHash13c(reinterpret_cast<const char *>(¶ms[0]), params.size() * sizeof(float));
                  ^
src\wren\StaticMesh.cpp:1481:19: style: Variable 'hash' is assigned a value that is never used. [unreadVariable]
    uint64_t hash = cache::sipHash13c(reinterpret_cast<const char *>(reinterpret_cast<const void *>(coordData)),
                  ^
src\wren\StaticMesh.cpp:1524:19: style: Variable 'hash' is assigned a value that is never used. [unreadVariable]
    uint64_t hash = cache::sipHash13c(reinterpret_cast<const char *>(reinterpret_cast<const void *>(coordData)),
                  ^
src\wren\StaticMesh.cpp:1589:12: style: Variable 'hash' is assigned a value that is never used. [unreadVariable]
      hash = ~hash;
           ^
```
https://ci.appveyor.com/project/omichel/webots-r0dha#L364

### PR DESCRIPTION
**Pull request by DavidMansolino**
Fix #1238

### CODE REVIEW

**Comment by DavidMansolino** [comment]
:+1:

**Comment by stefaniapedrazzi** [comment]
:eyes:

File: src/webots/nodes/WbBallJoint.cpp [hunk 1]
```diff
@@ -620,7 +620,8 @@ void WbBallJoint::prePhysicsStep(double ms) {
 
 void WbBallJoint::postPhysicsStep() {
   assert(mJoint);
-  if (motor() && motor()->isPIDPositionControl())
+  WbMotor *m1 = motor();
```
Comment (omichel) [inline src/webots/nodes/WbBallJoint.cpp]:
```suggestion
  const WbMotor *const m1 = motor();
```
