### PR TITLE
Fix Pen density

### LINKED ISSUE #2353: Wrong color blending when pen.inkdensity is not 1
**Describe the Bug**
> when I set inkdensity to intermediate amounts, it seems to average the pen color with white, rather than with whatever the existing color of the surface is, so it looks bad on surfaces that aren't naturally near-white

This is reproducible in the `pen.wbt` sample.

The blending with the `WorldInfo.inkEvaporation` factor works fine, the inkdensity should work the same way.

**Screenshots**
pen

**Additional context**

This is happenning both with Appearance and PBRAppearance.

### PR DESCRIPTION
**Pull request by lukicdarkoo**
Fixes #2353. 
image

The colors are now injected on top of the background, not on top of the white background.

This PR also changes how paint and texture colors are mixed, so it affects infra-red sensors as well. The `WbShape::pickColor`  method is a mess, we should get pixel color directly from WREN if possible.

### CODE REVIEW

**Comment by stefaniapedrazzi** [comment]
:eyes:

File: src/webots/nodes/WbShape.cpp [hunk 1]
```diff
@@ -387,9 +390,12 @@ void WbShape::pickColor(WbRgb &pickedColor, const WbRay &ray, double *roughness,
       return;  // default value
 
     // combine colors
-    pickedColor.setRed(diffuseColor.red() * textureColor.red() * paintColor.red());
-    pickedColor.setGreen(diffuseColor.green() * textureColor.green() * paintColor.green());
-    pickedColor.setBlue(diffuseColor.blue() * textureColor.blue() * paintColor.blue());
+    pickedColor.setRed((1 - paintContribution) * diffuseColor.red() * textureColor.red() +
```
Comment (stefaniapedrazzi) [inline src/webots/nodes/WbShape.cpp:393]: I would use a float value in these instructions so that the expected type is set (sometimes this could lead to errors):
```suggestion
    pickedColor.setRed((1.0f - paintContribution) * diffuseColor.red() * textureColor.red() +
```

**Review by stefaniapedrazzi — CHANGES_REQUESTED** [review]
Thank you! The blending is now working correctly.

I just have a couple of comment about the implementation.

**Comment by stefaniapedrazzi** [comment]
If this is affecting the result of the infra-red sensor, then maybe we should merge it into develop instead of master to be sure we don't break the compatibility (and add a bold warning text in the ChangeLog).

File: src/webots/nodes/utils/WbPaintTexture.cpp [hunk 2]
```diff
@@ -284,6 +286,24 @@ void WbPaintTexture::pickColor(WbRgb &pickedColor, const WbVector2 &uv) const {
...
+  while (y < 0)
+    y += h;
+  while (x >= w)
+    x -= w;
+  while (y >= h)
+    y -= h;
+
+  const int index = (y * w + x) * 4;
+  return mData[index + 3];
+}
```
[the remark this answers is not in the document]
Comment (lukicdarkoo) [reply src/webots/nodes/utils/WbPaintTexture.cpp:305]: You are completely right, I will change it

File: src/webots/nodes/utils/WbPaintTexture.cpp [hunk 3]
```diff
@@ -237,25 +237,27 @@ void WbPaintTexture::paint(const WbRay &ray, float leadSize, const WbRgb &color,
...
+        mData[dataIndex + 1] = oldDensityRatio * mData[dataIndex + 1] + (1 - oldDensityRatio) * color.green();
+        mData[dataIndex + 2] = oldDensityRatio * mData[dataIndex + 2] + (1 - oldDensityRatio) * color.red();
+        mData[dataIndex + 3] += density;
+        if (mData[dataIndex + 3] > 1)
+          mData[dataIndex + 3] = 1;
+
+        if (mEvaporation) {
+          mEvaporation[rowOffset + tx] += density;
+          if (mEvaporation[rowOffset + tx] > 1)
+            mEvaporation[rowOffset + tx] = 1;
```
[the remark this answers is not in the document]
Comment (lukicdarkoo) [reply src/webots/nodes/utils/WbPaintTexture.cpp:259]: No, the result should be the same? I will put 1.0f to be consistent

**Comment by lukicdarkoo** [comment]
> If this is affecting the result of the infra-red sensor, then maybe we should merge it into develop instead of master to be sure we don't break the compatibility (and add a bold warning text in the ChangeLog).

I don't know, it makes sense, but it is also a fix. It will affect the infra-red readings only in places where the paint is present. In a way, the previous readings were wrong (the sensors were reading the white color that is not painted).

**Comment by stefaniapedrazzi** [comment]
> > If this is affecting the result of the infra-red sensor, then maybe we should merge it into develop instead of master to be sure we don't break the compatibility (and add a bold warning text in the ChangeLog).
> 
> I don't know, it makes sense, but it is also a fix. It will affect the infra-red readings only in places where the paint is present. In a way, the previous readings were wrong (the sensors were reading the white color that is not painted).

Ok. So it is fine to merge to master.

File: src/webots/nodes/utils/WbPaintTexture.hpp [hunk 4]
```diff
@@ -39,7 +39,7 @@ class WbPaintTexture : public QObject {
 
   static bool isPaintable(const WbShape *shape);
 
-  void pickColor(WbRgb &pickedColor, const WbVector2 &uv) const;
+  void pickColor(WbRgb &pickedColor, const WbVector2 &uv, float *pickedDensity = NULL) const;
```
Comment (stefaniapedrazzi) [inline src/webots/nodes/utils/WbPaintTexture.hpp:42]: It is bad to mix input and output arguments, we should also change the function so that first the input arguments are given and then the output arguments:
```suggestion
  void pickColor(const WbVector2 &uv, WbRgb &pickedColor, float *pickedDensity = NULL) const;
```

File: src/webots/nodes/utils/WbPaintTexture.cpp [hunk 5]
```diff
@@ -237,25 +237,27 @@ void WbPaintTexture::paint(const WbRay &ray, float leadSize, const WbRgb &color,
...
-        mData[dataIndex] = existingColorPercentage * mData[dataIndex] + blue;
-        mData[dataIndex + 1] = existingColorPercentage * mData[dataIndex + 1] + green;
-        mData[dataIndex + 2] = existingColorPercentage * mData[dataIndex + 2] + red;
-        mData[dataIndex + 3] = 1.0f;
-
-        if (mEvaporation)
-          mEvaporation[rowOffset + tx] = 1.0f;
+        const float previousDensity = mData[dataIndex + 3];
+        const float oldDensityRatio = previousDensity / (density + previousDensity);
+        mData[dataIndex] = oldDensityRatio * mData[dataIndex] + (1 - oldDensityRatio) * color.blue();
```
Comment (stefaniapedrazzi) [inline src/webots/nodes/utils/WbPaintTexture.cpp:249]: I would use 1.0f also here
```suggestion
        mData[dataIndex] = oldDensityRatio * mData[dataIndex] + (1.0f - oldDensityRatio) * color.blue();
```

File: src/webots/nodes/WbShape.cpp [hunk 6]
```diff
@@ -387,9 +389,12 @@ void WbShape::pickColor(WbRgb &pickedColor, const WbRay &ray, double *roughness,
       return;  // default value
 
     // combine colors
-    pickedColor.setRed(diffuseColor.red() * textureColor.red() * paintColor.red());
-    pickedColor.setGreen(diffuseColor.green() * textureColor.green() * paintColor.green());
-    pickedColor.setBlue(diffuseColor.blue() * textureColor.blue() * paintColor.blue());
+    pickedColor.setRed((1.0f - paintContribution) * diffuseColor.red() * textureColor.red() +
+                       paintContribution * paintColor.red());
+    pickedColor.setGreen((1 - paintContribution) * diffuseColor.green() * textureColor.green() +
```
Comment (stefaniapedrazzi) [inline src/webots/nodes/WbShape.cpp:394]:
```suggestion
    pickedColor.setGreen((1.0f - paintContribution) * diffuseColor.green() * textureColor.green() +
```

File: src/webots/nodes/WbShape.cpp [hunk 7]
```diff
@@ -387,9 +389,12 @@ void WbShape::pickColor(WbRgb &pickedColor, const WbRay &ray, double *roughness,
...
+                         paintContribution * paintColor.green());
+    pickedColor.setBlue((1 - paintContribution) * diffuseColor.blue() * textureColor.blue() +
```
Comment (stefaniapedrazzi) [inline src/webots/nodes/WbShape.cpp:396]:
```suggestion
    pickedColor.setBlue((1.0f - paintContribution) * diffuseColor.blue() * textureColor.blue() +
```

File: src/webots/nodes/utils/WbPaintTexture.cpp [hunk 8]
```diff
@@ -237,25 +237,27 @@ void WbPaintTexture::paint(const WbRay &ray, float leadSize, const WbRgb &color,
...
+        mData[dataIndex + 1] = oldDensityRatio * mData[dataIndex + 1] + (1 - oldDensityRatio) * color.green();
```
Comment (stefaniapedrazzi) [inline src/webots/nodes/utils/WbPaintTexture.cpp:250]:
```suggestion
        mData[dataIndex + 1] = oldDensityRatio * mData[dataIndex + 1] + (1.0f - oldDensityRatio) * color.green();
```

File: src/webots/nodes/utils/WbPaintTexture.cpp [hunk 9]
```diff
@@ -237,25 +237,27 @@ void WbPaintTexture::paint(const WbRay &ray, float leadSize, const WbRgb &color,
...
+        mData[dataIndex + 2] = oldDensityRatio * mData[dataIndex + 2] + (1 - oldDensityRatio) * color.red();
```
Comment (stefaniapedrazzi) [inline src/webots/nodes/utils/WbPaintTexture.cpp:251]:
```suggestion
        mData[dataIndex + 2] = oldDensityRatio * mData[dataIndex + 2] + (1.0f - oldDensityRatio) * color.red();
```

**Review by stefaniapedrazzi — CHANGES_REQUESTED** [review]
Thank you.

I would use 1.0f for all the density computations.

File: src/webots/nodes/utils/WbPaintTexture.hpp (hunk 4 above)
Comment (lukicdarkoo) [reply src/webots/nodes/utils/WbPaintTexture.hpp:42]: I was hoping to avoid changing the other parts of the code. I will revert to `pickDensity()` as changing the order will affect other parts of the code and cause inconsistency. For example `WbAppearance::pickColorInTexture(WbRgb &pickedColor, const WbVector2 &uv)` will not be consistent with `WbPaintTexture::pickColor(const WbVector2 &uv, WbRgb &pickedColor, float *pickedDensity = NULL)` (argument order is reversed).

Comment (stefaniapedrazzi) [reply src/webots/nodes/utils/WbPaintTexture.hpp:42]: I think that we should consider reversing the arguments in all the functions.
It is standard to have first input and then output arguments.

**Review by stefaniapedrazzi — APPROVED** [review]
Thank you!
