### PR TITLE
Launch Webots on x11 server

### LINKED ISSUE #6732: 3D scene mouse interaction problems
**Describe the Bug**
When interacting with the 3D scene in Webots R2025a, two issues occur:

I. Right clicking on the 3D scene opens multiple context menu.

**Steps to Reproduce**
1. Start any simulation
2. Right click on the 3D scene multiple times
3. More than one context menu appears

**Screenshots**
context_menu

**Expected behavior**
Only one context menu should appear in the 3D scene at any given time.

II. For example, in the moose_demo.wbt simulation:
After left-clicking on the 3D scene, you should be able to control (teleoperate) the moose robot.

**Steps to Reproduce**
1. Start  the simulation from the moose_demo.wbt world
2. Left-clicking on the 3D scene
3. Telepoerate the robot
4. Left-clicking on the 3D scene does not enable teleoperation as expected.

**Expected behavior**
Left-clicking on the 3D scene should enable teleoperation for the selected robot.

**System**
 - Operating System: Ubuntu 24.04
 - Graphics Card: Intel® UHD Graphics 620 (WHL GT2)

**Additional context**
 This bug appeared in Webots R2025a (debian package) from QA testing.

### LINKED ISSUE #6733: Webots icon not visible
**Describe the Bug**
When launching Webots, the Webots icon is not visible

**Steps to Reproduce**
1. Start Webots R2025a

**Expected behavior**
The Webots icon should be visible.

**Screenshots**
webots_logo

**System**
 - Operating System: Ubuntu 24.04
 - Graphics Card: Intel® UHD Graphics 620 (WHL GT2)

**Additional context**
 This bug appeared in Webots R2025a (debian package) from QA testing.

### PR DESCRIPTION
**Pull request by MNikoliCC**
**Description**
Lanching Webots on x11 server solves the issues.

**Related Issues**
Fixes #6732
Fixes #6733

**Tasks**
Add the list of tasks of this PR.
  - [x] Fix mouse interaction issue
  - [x] Fix icon issue

### CODE REVIEW

**Review by lukicdarkoo — CHANGES_REQUESTED** [review]
To be more consistent I would rather export it as the other env variables, e.g. above:
```
# Fix for i3 window manager not working with Qt6
```
and also add a comment why the variable exists (Wayland copmability).

File: src/webots/launcher/webots-linux.sh [hunk 1]
```diff
@@ -87,6 +98,11 @@ else
   export QT_ENABLE_HIGHDPI_SCALING=1
 fi
 
+# set the x11 server for Ubuntu 24 version
```
Comment (MNikoliCC) [inline src/webots/launcher/webots-linux.sh:101]: Based on the Ubuntu version the _x11_ server is exported
