### PR TITLE
Fix macOS contents path

### LINKED ISSUE #4761: macOS: wrong path for objects PROTO controller paths
**Describe the Bug**
Paths for controllers in the `objects` directory are not found correctly in the macOS .dmg package.
The `Contents` directory is missing in the path.
The path for compiling controllers is also wrong and does not contain `Contents`.

### PR DESCRIPTION
**Pull request by ThomasOliverKimble**
**Description**
Continue fix #4761 as Contents was missing from vehicle library paths.

### CODE REVIEW

**Comment by ThomasOliverKimble** [comment]
> Thank you.

I just found another place where it is not updated, I will go through the webots guided tour and devices tour to double check before marking this PR as ready for review.

File: projects/robots/robotis/darwin-op/libraries/managers/src/RobotisOp2DirectoryManager.cpp [hunk 1]
```diff
@@ -28,7 +28,12 @@ const string &RobotisOp2DirectoryManager::getDataDirectory() {
   static string path = "/robotis/Data/";
 #else
   char *WEBOTS_HOME = wbu_system_getenv("WEBOTS_HOME");
-  static string path = string(WEBOTS_HOME) + "/projects/robots/robotis/darwin-op/libraries/robotis-op2/robotis/Data/";
+  static string path = string(WEBOTS_HOME)
+#ifdef __APPLE__
+                       + "Contents/projects/robots/robotis/darwin-op/libraries/robotis-op2/robotis/Data/";
+#else
+                       + "/projects/robots/robotis/darwin-op/libraries/robotis-op2/robotis/Data/";
+#endif
```
Comment (omichel) [inline projects/robots/robotis/darwin-op/libraries/managers/src/RobotisOp2DirectoryManager.cpp:36]: Let's avoid redundancy:
```suggestion
#ifdef __APPLE__
                       + "Contents/";
#endif
                       + "/projects/robots/robotis/darwin-op/libraries/robotis-op2/robotis/Data/";
```

**Review by omichel — APPROVED** [review]
