### PR TITLE
Fixed absolute EXTERNPROTO path

### LINKED ISSUE #4950: Consistency between absolute and relative EXTERNPROTO path
Error message about missing EXTERNPROTO declaration is suggesting an absolute path for a local PROTO file.
It tells to add the following line to the parent PROTO file:
``EXTERNPROTO "/home/stefi/Desktop/test_project1/protos/MyJoint.proto"``

However when inserting a node in the world from the scene tree the added path is:
``EXTERNPROTO "../protos/MyJoint.proto"``

### PR DESCRIPTION
**Pull request by omichel**
Fixes #4950.

We should never suggest a user to declare an EXTERNPROTO with an absolute path.

### CODE REVIEW

File: src/webots/vrml/WbProtoManager.cpp [hunk 1]
```diff
@@ -144,14 +144,13 @@ WbProtoModel *WbProtoManager::findModel(const QString &modelName, const QString
...
-      if (!protoDeclaration.isEmpty() || isProtoInCategory(modelName, PROTO_WEBOTS))
-        errorMessage = tr("Missing declaration for '%1', add: 'EXTERNPROTO \"%2\"' to '%3'.")
-                         .arg(modelName)
-                         .arg(protoDeclaration.isEmpty() ? mWebotsProtoList.value(modelName)->url() : protoDeclaration)
-                         .arg(parentFilePath);
-      else
-        errorMessage = tr("Missing declaration for '%1', unknown node.").arg(modelName);
+      const QString url = protoDeclaration.isEmpty() ?
+                            mWebotsProtoList.value(modelName)->url() :
+                            QDir(WbProject::current()->worldsPath()).relativeFilePath(protoDeclaration);
```
Comment (ad-daniel) [inline src/webots/vrml/WbProtoManager.cpp:149]:
```suggestion
                            QDir(QFileInfo(mCurrentWorld).absolutePath()).relativeFilePath(protoDeclaration);
```

**Review by ad-daniel — APPROVED** [review]
Thank you
