### PR TITLE
Fix check in WbServer.js

### LINKED ISSUE #4129: small bug in streaming viewer wwi/Server.js
**Describe the Bug**
**Path:**  resources/web/wwi/Server.js
Inside onMessage(event) function, there should be a judgement before accessing this._view.x3dScene
Otherwise, streaming headless mjpeg will get an exception on it.

Current:
```
this._view.x3dScene.prefix = this._httpServerUrl + '/';
```
Expected:  
```
if (typeof this._view.x3dScene !== 'undefined')
    this._view.x3dScene.prefix = this._httpServerUrl + '/';
```

### PR DESCRIPTION
**Pull request by BenjaminDeleze**
**Description**
Fix #4129

### CODE REVIEW

File: resources/web/wwi/Server.js [hunk 1]
```diff
@@ -23,7 +23,8 @@ export default class Server {
   connect() {
     const n = this._url.indexOf('/session?url=', 6);
     const url = 'http' + (n > 0 ? this._url.substring(2, n + 8) : this._url.substring(2, this._url.indexOf('/', 6)) + '/session');
-    document.getElementById('webotsProgressMessage').innerHTML = 'Connecting to session server...';
+    if (document.getElementById('webotsProgressMessage'))
+      document.getElementById('webotsProgressMessage').innerHTML = 'Connecting to session server...';
```
Comment (omichel) [inline resources/web/wwi/Server.js:27]: There is bit of redundancy here. What about this:
```suggestion
    let progressMessage = document.getElementById('webotsProgressMessage'))
    if (progressMessage)
      progressMessage.innerHTML = 'Connecting to session server...';
```

File: resources/web/wwi/Server.js [hunk 2]
```diff
@@ -72,7 +73,8 @@ export default class Server {
       const host = location.protocol + '//' + location.host.replace(/^www./, ''); // remove 'www' prefix
       this.socket.send('{ "init" : [ "' + host + '", "' + this._project + '", "' + this._worldFile + '" ] }');
     }
-    document.getElementById('webotsProgressMessage').innerHTML = 'Starting simulation...';
+    if (document.getElementById('webotsProgressMessage'))
+      document.getElementById('webotsProgressMessage').innerHTML = 'Starting simulation...';
```
Comment (omichel) [inline resources/web/wwi/Server.js:77]: Same comment here:
```suggestion
    let progressMessage = document.getElementById('webotsProgressMessage'))
    if (progressMessage)
      progressMessage.innerHTML = 'Starting simulation...';
```

**Review by omichel — COMMENTED** [review]
It looks good to me, I just have a suggestion.

**Review by omichel — APPROVED** [review]
Thank you.
