### PR TITLE
Fix warning missing icon

### LINKED ISSUE #5066: Remote PROTO without icon throw download warning
**Describe the Bug**

Take this example of world, the PROTO is downloaded from a remote url outside our own. When selecting this PROTO in the add-node window, a warning is shown saying that the icon could not be downloaded (none exists in the repo). By printing the error message we're essentially forcing people to define an icon for their PROTO which isn't ideal. If it couldn't be downloaded we should either show nothing (as we do for local proto) or show a default one, without printing any warning.

```
#VRML_SIM R2022b utf8

EXTERNPROTO "https://raw.githubusercontent.com/cyberbotics/webots-cloud-simulation-examples/main/7_local_assets/protos/MyProto.proto"

WorldInfo {
}
Viewpoint {
  orientation -0.0316302248353415 0.02843866445440257 0.9990949760863156 1.6779495280745207
  position -0.05753688709726134 2.5600691798403346 9.999992923742619
}
Background {
  skyColor 0.5 0.5 0.8
}
MyProto {
}
```

EDIT: if the link of the EXTERNPROTO does not work, use: 
```
EXTERNPROTO "https://raw.githubusercontent.com/cyberbotics/webots-cloud-simulation-examples/test-protos-download/7_local_assets/protos/MyProto.proto"
```

### PR DESCRIPTION
**Pull request by BenjaminDeleze**
Fix #5066

### CODE REVIEW

File: src/webots/nodes/utils/WbUrl.cpp [hunk 1]
```diff
@@ -38,6 +38,11 @@ const QString &WbUrl::missingTexture() {
   return missingTexture;
 }
 
+const QString &WbUrl::missingIcon() {
+  const static QString missingIcon = WbStandardPaths::resourcesPath() + "images/missing_icon.png";
+  return missingIcon;
+}
+
```
Comment (omichel) [inline src/webots/nodes/utils/WbUrl.cpp:45]: I believe it is better to be more precise with naming:
```suggestion
const QString &WbUrl::missingProtoIcon() {
  const static QString missingProtoIcon = WbStandardPaths::resourcesPath() + "images/missing_proto_icon.png";
  return missingProtoIcon;
}

```

**Review by ygoumaz — APPROVED** [review]
Seems to work smoothly! Thank you.

**Comment by omichel** [comment]
The image should be renamed as well.

**Review by omichel — APPROVED** [review]

**Review by ygoumaz — APPROVED** [review]
