### PR TITLE
Fixed Background VRML Export.

### LINKED ISSUE #1866: VRML Export-Import Fail with Background Node
**Describe the Bug**
When exporting a node to VRML and then re-importing this node, the importation of the background node fails with this warning:
```
WARNING: Background: Cannot load texture '/home/david/webots/projects/samples/devices/worlds/textures/cubic/mountains_right.hdr': Unsupported image format.
```

### PR DESCRIPTION
**Pull request by DavidMansolino**
**Description**
Fix #1866.

### CODE REVIEW

File: src/webots/nodes/WbBackground.cpp [hunk 1]
```diff
@@ -469,7 +469,7 @@ void WbBackground::exportNodeFields(WbVrmlWriter &writer) const {
     for (int i = 0; i < 6; ++i) {
       if (!irradianceFileNames[i].isEmpty()) {
```
Comment (omichel) [inline src/webots/nodes/WbBackground.cpp:470]:
```suggestion
      if (!backgroundFileNames[i].isEmpty()) {
```
