### PR TITLE
Fix declaration of EXTERNPROTO in new world

### LINKED ISSUE #4725: Textures not found in custom world created with snap package on Ubuntu 22.04
Steps to reproduce:
1) open `acceleremeter.wbt`
2) create a new project with the wizard
3) stop simulation
4) add an E-puck robot
5) move viewpoint to the robot
6) save world
7) close webots
8) restart webots
-> errors about textures of TexturedBackground not found

It seems that there are some conflicts, because after this any world containing the TextureBaground will throw errors.
However, if you open a default world (for example `accelerometer.wbt`) and restart Webots no error is displayed.

### PR DESCRIPTION
**Pull request by stefaniapedrazzi**
Fix #4725:

generate new world instead of copying the `resources/projects/worlds/empty.wbt` file when creating a new project from the wizard and add the required EXTERNPROTO declarations.

### CODE REVIEW

File: src/webots/gui/WbNewProjectWizard.cpp [hunk 1]
```diff
@@ -89,58 +91,75 @@ WbNewProjectWizard::~WbNewProjectWizard() {
...
+  if (mBackgroundCheckBox->isChecked()) {
+    externProtoList << "TexturedBackground";
+    if (mDirectionalLightCheckBox->isChecked())
+      externProtoList << "TexturedBackgroundLight";
+  }
+  if (mArenaCheckBox->isChecked())
+    externProtoList << "RectangleArena";
+  foreach (const QString &protoModel, externProtoList) {
+    const QString &modelPath = WbProtoManager::instance()->findModelPath(protoModel);
+    qDebug() << "modelPath" << protoModel << modelPath;
```
Comment (omichel) [inline src/webots/gui/WbNewProjectWizard.cpp:118]:
```suggestion
```

**Review by omichel — CHANGES_REQUESTED** [review]

File: src/webots/gui/WbNewProjectWizard.cpp [hunk 2]
```diff
@@ -89,58 +91,74 @@ WbNewProjectWizard::~WbNewProjectWizard() {
 }
 
 void WbNewProjectWizard::accept() {
-  bool success = mProject->createNewProjectFiles(mWorldEdit->text());
+  mIsValidProject = true;
+
+  if (!mProject->createNewProjectFolders()) {
+    WbMessageBox::warning(tr("Some directories or files could not be created."), this, tr("File creation failed"));
```
Comment (omichel) [inline src/webots/gui/WbNewProjectWizard.cpp:97]:
```suggestion
    WbMessageBox::warning(tr("Some directories could not be created."), this, tr("Directories creation failed"));
```

**Review by omichel — CHANGES_REQUESTED** [review]

**Review by omichel — COMMENTED** [review]
Thank you.
