### PR TITLE
Simplify tmp directory computation for extern controllers

### LINKED ISSUE #5300: Search for Webots tmp directory in libController is not robust
If a snap installation of Webots is found on the system but another Webots (git clone, tarball, or debian) version is currently executed, the libController uses the snap `tmp` directory for connecting extern controllers and fails to connect instead of checking if the Webots instance files exists and reverting to the system `tmp` folder.

### PR DESCRIPTION
**Pull request by ygoumaz**
Fixes #5300.

The `wbu_system_dir()` function is only used to get the tmp dir when using **ipc extern** controllers. The `WEBOTS_TMPDIR` is not useful and can be discarded in this case. Instead we use `WEBOTS_HOME` to determine if we target a snap installation of Webots. If not we default to `/tmp`.

This PR also updates the `test_sources` to Ubuntu 22 to fix some cppcheck false positives. The clang-format version is locked to 14.0.0.

### CODE REVIEW

**Review by omichel — APPROVED** [review]
Looks good to me.
Thank you.

File: src/webots/nodes/WbCharger.cpp [hunk 1]
```diff
@@ -104,7 +104,8 @@ void WbCharger::updateMaterialsAndLights(double batteryRatio) {
     WbPbrAppearance *appearance = dynamic_cast<WbPbrAppearance *>(visualElement->node);
     WbLight *light = dynamic_cast<WbLight *>(visualElement->node);
     const WbRgb color(cr, cg, cb);
-    assert(!WbRgb(cr, cg, cb).clampValuesIfNeeded());
+    const bool clampNeeded = WbRgb(cr, cg, cb).clampValuesIfNeeded();
+    assert(!clampNeeded);
```
Comment (omichel) [inline src/webots/nodes/WbCharger.cpp:108]: This broke the nightly builds, see https://github.com/cyberbotics/webots/actions/runs/4527046581/jobs/7972592389

File: src/webots/nodes/WbRobot.cpp [hunk 2]
```diff
@@ -158,7 +158,18 @@ WbRobot::WbRobot(WbTokenizer *tokenizer) : WbSolid("Robot", tokenizer) {
   init();
 }
 
-WbRobot::WbRobot(const WbRobot &other) : WbSolid(other) {
+WbRobot::WbRobot(const WbRobot &other) :
+  WbSolid(other),
+  mControllerDir(),
```
Comment (stefaniapedrazzi) [inline src/webots/nodes/WbRobot.cpp:163]: All these initialization lines are useless and should be removed because QString are already initialized by default.

File: src/webots/nodes/WbReceiver.cpp [hunk 3]
```diff
@@ -117,7 +117,7 @@ WbReceiver::WbReceiver(WbTokenizer *tokenizer) : WbSolidDevice("Receiver", token
   init();
 }
 
-WbReceiver::WbReceiver(const WbReceiver &other) : WbSolidDevice(other) {
+WbReceiver::WbReceiver(const WbReceiver &other) : WbSolidDevice(other), mTransmissionList(), mWaitingQueue(), mReadyQueue() {
```
Comment (stefaniapedrazzi) [inline src/webots/nodes/WbReceiver.cpp:120]: The newly added initialization instructions are useless and should be removed.

File: src/webots/nodes/WbSkin.cpp [hunk 4]
```diff
@@ -81,7 +81,20 @@ WbSkin::WbSkin(WbTokenizer *tokenizer) : WbBaseNode("Skin", tokenizer), WbAbstra
...
+  mInitialSkeletonOrientation(),
+  mInitialSkeletonPosition(),
+  mRenderables(),
+  mMaterialNames(),
+  mMaterials(),
+  mSegmentationMaterials(),
+  mEncodeDepthMaterials(),
+  mMeshes(),
+  mBoneTransforms(),
+  mBonesMap() {
```
[the remark this answers is not in the document]
Comment (ygoumaz) [reply src/webots/nodes/WbSkin.cpp:97]: cppcheck triggers an error if they are missing.

File: src/webots/nodes/WbReceiver.cpp (hunk 3 above)
Comment (ygoumaz) [reply src/webots/nodes/WbReceiver.cpp:120]: cppcheck triggers an error if they are missing.

File: src/webots/nodes/WbRobot.cpp (hunk 2 above)
Comment (ygoumaz) [reply src/webots/nodes/WbRobot.cpp:163]: cppcheck triggers an error if they are missing.

File: src/webots/nodes/WbLightSensor.cpp [hunk 5]
```diff
@@ -134,7 +134,7 @@ WbLightSensor::WbLightSensor(WbTokenizer *tokenizer) : WbSolidDevice("LightSenso
   init();
 }
 
-WbLightSensor::WbLightSensor(const WbLightSensor &other) : WbSolidDevice(other) {
+WbLightSensor::WbLightSensor(const WbLightSensor &other) : WbSolidDevice(other), mRayList() {
```
Comment (stefaniapedrazzi) [inline src/webots/nodes/WbLightSensor.cpp:137]: It useless to explicitly initialize `mRayList` to the default value.

File: src/webots/nodes/WbLed.cpp [hunk 6]
```diff
@@ -38,7 +38,7 @@ WbLed::WbLed(WbTokenizer *tokenizer) : WbSolidDevice("LED", tokenizer) {
   init();
 }
 
-WbLed::WbLed(const WbLed &other) : WbSolidDevice(other) {
+WbLed::WbLed(const WbLed &other) : WbSolidDevice(other), mMaterials(), mPbrAppearances(), mLights() {
```
Comment (stefaniapedrazzi) [inline src/webots/nodes/WbLed.cpp:41]: here as well, the new initialization instructions are useless.

File: src/webots/nodes/WbRobot.cpp (hunk 2 above)
Comment (stefaniapedrazzi) [reply src/webots/nodes/WbRobot.cpp:163]: Ok. But the cppcheck error/warning is wrong.

Comment (ygoumaz) [reply src/webots/nodes/WbRobot.cpp:163]: I don't know if using a lot of suppress tags for cppcheck is really the best solution. Is it really that bad to initialize those QString objects?

Comment (stefaniapedrazzi) [reply src/webots/nodes/WbRobot.cpp:163]: It is completely useless to explicitly initialize the strings and all the other Qt objects
From my point of view it makes the code less readable than before because we have a long list of useless instructions.
I think that cppcheck should help us writing better code, not worse and lately it is not always the case.
We should try to adjust the configuration to try to avoid these false positives.
