### PR TITLE
Fix crash due to invalid SFColor value

### LINKED ISSUE #3183: nao_demo crash
**Steps to Reproduce**
1. Open nao_demo.wbt
2. Open the Nao proto in the scene tree
3. Select a color to replace the default color which is strangely -1 -1 -1
4. Reset the color field to its default value (-1 -1 -1) from the popup menu.
5. Click on the next field in the Nao proto: controller.
6. Webots crashes 😒

**System**
 - Operating System: Windows 10

### PR DESCRIPTION
**Pull request by stefaniapedrazzi**
Fix #3183:
do not allow use of invalid SFColor values in PROTO parameters.
If invalid values are defined, they are clamped to the valid range [0.0, 1.0] and an error is printed in the console.

### CODE REVIEW

File: src/webots/vrml/WbMFColor.cpp [hunk 1]
```diff
@@ -20,7 +20,17 @@ void WbMFColor::readAndAddItem(WbTokenizer *tokenizer, const QString &worldPath)
...
   const double g = tokenizer->nextToken()->toDouble();
   const double b = tokenizer->nextToken()->toDouble();
-  mVector.append(WbRgb(r, g, b));
+  WbRgb color(r, g, b);
+  if (color.clampValuesIfNeeded())
+    tokenizer->reportError(
+      tr("Expected positive color values in range [0.0, 1.0], found [%1 %2 %3]. MFColor field item reset to [%4 %5 %6]")
+        .arg(r)
+        .arg(g)
+        .arg(b)
```
Comment (omichel) [inline src/webots/vrml/WbMFColor.cpp:29]: That may help to identify the bad guy in a MFColor field:
```suggestion
      tr("Expected positive color values in range [0.0, 1.0], found [%1 %2 %3]. MFColor field item %4 reset to [%5 %6 %7]")
        .arg(r)
        .arg(g)
        .arg(b)
        .arg(mVector.size())
```

**Review by omichel — APPROVED** [review]
Thank you.
It looks very good to me.
I just have a minor suggestion.

**Review by omichel — APPROVED** [review]
Thank you.
