### PR TITLE
Fix mac pythonpath

### LINKED ISSUE #3285: Webots doesn't find the Python executable when running from Spotlight
The following works as expected:
```
% python3.8 --version
Python 3.8.5
% /Applications/Webots.app/webots /Applications/Webots.app/projects/languages/python/worlds/example.wbt
```

But when running the same world in Webots executed from the GUI Webots fails to find the Python executable.

**System**
 - Operating System: macOS

### PR DESCRIPTION
**Pull request by BenjaminDeleze**
**Description**
The python executable is not found on MacOS when launching Webots from the GUI (Spotlight, Finder, Dock). 

To fix that, we decided to hardcode the standard MacOS path to both python from python.org and python from homebrew in Webots.
It it does not work, a warning will be displayed, requesting the user to set the full path to his python executable in the preferences of webots.

Fix #3285.

### CODE REVIEW

File: src/webots/control/WbLanguageTools.cpp [hunk 1]
```diff
@@ -63,7 +63,11 @@ const QStringList WbLanguageTools::javaArguments() {
 
 QString WbLanguageTools::pythonCommand(QString &shortVersion, const QString &command, QProcessEnvironment &env) {
   QString pythonCommand = command;
-  const QString advice =
+  QString advice =
+#ifdef __APPLE__
+    "To fix the problem, you could try to insert the full path of your python distribution in "
```
Comment (omichel) [inline src/webots/control/WbLanguageTools.cpp:68]:
```suggestion
    "To fix the problem, you should set the full path of your python command in "
```

File: src/webots/control/WbLanguageTools.cpp [hunk 2]
```diff
@@ -63,7 +63,11 @@ const QStringList WbLanguageTools::javaArguments() {
 
 QString WbLanguageTools::pythonCommand(QString &shortVersion, const QString &command, QProcessEnvironment &env) {
   QString pythonCommand = command;
-  const QString advice =
+  QString advice =
```
Comment (omichel) [inline src/webots/control/WbLanguageTools.cpp:66]: Can't we keep it const?
```suggestion
  const QString advice =
```

File: src/webots/control/WbLanguageTools.hpp [hunk 3]
```diff
@@ -35,6 +35,9 @@ class WbLanguageTools {
 private:
   WbLanguageTools() {}
   ~WbLanguageTools() {}
+  static const QString checkIfPythonCommandExist(const QString &pythonCommand, QProcessEnvironment &env, bool log);
+  // cppcheck-suppress unusedPrivateFunction
+  static QString findWorkingPath(const QString &pythonVersion, QProcessEnvironment &env, bool log);
```
Comment (omichel) [inline src/webots/control/WbLanguageTools.hpp:40]: That method seems to be specific to python, so I would add "python" in its name:
```suggestion
  static QString findWorkingPythonPath(const QString &pythonVersion, QProcessEnvironment &env, bool log);
```

File: src/webots/control/WbLanguageTools.hpp [hunk 4]
```diff
@@ -35,6 +35,9 @@ class WbLanguageTools {
 private:
   WbLanguageTools() {}
   ~WbLanguageTools() {}
+  static const QString checkIfPythonCommandExist(const QString &pythonCommand, QProcessEnvironment &env, bool log);
+  // cppcheck-suppress unusedPrivateFunction
```
Comment (omichel) [inline src/webots/control/WbLanguageTools.hpp:39]: Instead of `cppcheck-suppress unusedPrivateFunction`, we should declare and implement this function only in the macOS case (using `#ifdef`).

**Review by omichel — CHANGES_REQUESTED** [review]
That looks good to me.
I have a couple of minor suggestions.

**Review by omichel — APPROVED** [review]
Thank you.
