### PR TITLE
Enhance thumbnail upload robustness

### LINKED ISSUE #4654: Thumbnail not always uploading to cloud
**Describe the Bug**
Sometimes when uploading to `webots.cloud`: `share`->`upload to webots.cloud`->`Record and export animation` or `Export scene`, the thumbnail is not saved in time for the upload and therefore is ignored and not uploaded to the server.

### PR DESCRIPTION
**Pull request by ThomasOliverKimble**
**Description**
Fixes #4654: Checks for files 10 times every 100ms, if they don't exist, don't try and upload them.

### CODE REVIEW

File: src/webots/gui/WbMainWindow.cpp [hunk 1]
```diff
@@ -1747,6 +1747,21 @@ void WbMainWindow::uploadStatus() {
     WbMessageBox::critical(tr("Upload failed: Upload status could not be modified."));
 }
 
+bool WbMainWindow::uploadFileExists(QString filename) {
+  int maxIterations = 10;
+  while (!QFileInfo(WbStandardPaths::webotsTmpPath() + filename).exists() && maxIterations) {
+    QTime delay = QTime::currentTime().addMSecs(100);
+    while (QTime::currentTime() < delay)
+      QCoreApplication::processEvents(QEventLoop::AllEvents);
```
Comment (omichel) [inline src/webots/gui/WbMainWindow.cpp:1755]: Calling `QCoreApplication::processEvents` in an active loop is probably super computer intensive. I believe we should avoid this:
```suggestion
    QCoreApplication::processEvents(QEventLoop::AllEvents, 100);
```

**Review by omichel — CHANGES_REQUESTED** [review]

File: src/webots/gui/WbMainWindow.cpp (hunk 1 above)
Comment (ThomasOliverKimble) [reply src/webots/gui/WbMainWindow.cpp]: I have changed this for a QThread::msleep(100) instead.

**Review by omichel — APPROVED** [review]
Better this way indeed.
Thank you.

**Review by omichel — APPROVED** [review]
